import { useParams, useNavigate } from 'react-router-dom';
import { useStore } from '../store/useStore';
import { useEffect } from 'react';

const Report = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { analyses, standards, markAnalysisReviewed } = useStore();
  
  const analysis = analyses.find(a => a.id === id);

  useEffect(() => {
    if (analysis && analysis.reviewStatus !== 'Reviewed') {
      markAnalysisReviewed(analysis.id);
    }
  }, [analysis, markAnalysisReviewed]);

  if (!analysis) return <div className="p-8">Analysis not found.</div>;

  const acceptedRecs = analysis.recommendations.filter(r => r.reviewerDecision === 'Accept');
  const otherRecs = analysis.recommendations.filter(r => r.reviewerDecision !== 'Accept');

  return (
    <div>
      <div className="flex justify-between items-center mb-6 print:hidden">
        <div>
          <h1 className="text-2xl font-semibold mb-1">Procurement Standards Report</h1>
          <p className="text-text-secondary">Generated by StandardsAI</p>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-secondary" onClick={() => window.print()}>Print / Save PDF</button>
          <button className="btn btn-primary" onClick={() => navigate('/history')}>Done</button>
        </div>
      </div>

      <div className="card max-w-4xl mx-auto md:p-12 print:border-none print:shadow-none print:p-0 print:m-0 print:max-w-none">
        <div className="border-b-2 border-accent-900 pb-4 mb-8">
          <h2 className="text-3xl font-bold text-accent-900">Official Standards Recommendation Report</h2>
          <div className="flex justify-between mt-4 text-sm text-text-secondary">
            <span>Date: {new Date().toLocaleDateString()}</span>
            <span>Ref: {analysis.id}</span>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-semibold border-b border-border pb-2 mb-4">1. Procurement Specification Summary</h3>
          <div className="grid grid-cols-2 gap-4">
            <div><span className="font-semibold text-text-primary">Category:</span> {analysis.category}</div>
            <div><span className="font-semibold text-text-primary">Analysis Date:</span> {new Date(analysis.createdAt).toLocaleDateString()}</div>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-semibold border-b border-border pb-2 mb-4">2. Extracted Requirements</h3>
          <ul className="list-disc pl-5 space-y-1">
            {analysis.extractedRequirements.map((req, i) => (
              <li key={i}>{req}</li>
            ))}
          </ul>
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-semibold border-b border-border pb-2 mb-4">3. Accepted Standards for Inclusion</h3>
          {acceptedRecs.length > 0 ? (
            <div className="flex flex-col gap-4">
              {acceptedRecs.map(rec => {
                const std = standards.find(s => s.id === rec.standardId);
                if (!std) return null;
                return (
                  <div key={rec.id} className="bg-primary p-4 rounded-md border border-border print:break-inside-avoid">
                    <div className="font-bold text-lg text-text-primary">{std.number}</div>
                    <div className="font-medium text-text-secondary mb-2">{std.title}</div>
                    <div className="text-sm">
                      <span className="font-semibold">Role:</span> {rec.relationshipType}
                    </div>
                    <div className="mt-2 pt-2 border-t border-border text-sm italic">
                      "{std.evidenceExcerpt}"
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <p className="text-text-secondary italic">No standards were accepted during review.</p>
          )}
        </div>

        <div className="mb-8">
          <h3 className="text-lg font-semibold border-b border-border pb-2 mb-4">4. Other Reviewed Standards</h3>
          {otherRecs.length > 0 ? (
            <div className="table-container">
              <table className="w-full text-sm">
                <thead>
                  <tr>
                    <th className="text-left pb-2">Standard</th>
                    <th className="text-left pb-2">Decision</th>
                  </tr>
                </thead>
                <tbody>
                  {otherRecs.map(rec => {
                    const std = standards.find(s => s.id === rec.standardId);
                    if (!std) return null;
                    return (
                      <tr key={rec.id} className="border-t border-border">
                        <td className="py-2">{std.number}</td>
                        <td className="py-2">{rec.reviewerDecision || 'Pending'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          ) : (
            <p className="text-text-secondary italic">No other standards were reviewed.</p>
          )}
        </div>

        <div className="mt-16 pt-8 border-t-2 border-dashed border-border print:break-inside-avoid">
          <h3 className="text-lg font-semibold mb-4">Verification Sign-off</h3>
          <div className="h-24 border border-border rounded-md bg-primary mb-4 print:bg-transparent"></div>
          <div className="flex justify-between">
            <div>
              <div className="border-b border-black w-48 h-10"></div>
              <div className="text-sm mt-1 font-medium">Reviewer Signature</div>
            </div>
            <div>
              <div className="border-b border-black w-32 h-10"></div>
              <div className="text-sm mt-1 font-medium">Date</div>
            </div>
          </div>
          <p className="text-xs text-text-muted mt-8 text-center print:block">
            Recommendations are AI-assisted and must be verified by an authorized technical/procurement professional before use in a tender specification.
          </p>
        </div>
      </div>
      <style>{`
        @media print {
          @page { margin: 20mm; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
      `}</style>
    </div>
  );
};

export default Report;
